MisPerris/MisPerris/MisPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [  
    url('admin/', admin.site.urls),
    url(r'^$',LoginView.as_view(template_name = 'index.html'), name='login'),
    url('adopcion/', include ('apps.adopcion.urls',namespace="adopcion")),
    url('mascota/',include ('apps.mascota.urls',namespace="mascota")),
    url('usuario/',include ('apps.usuario.urls',namespace="usuario")),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^accounts/login',LoginView.as_view(template_name = 'index.html'), name='login2'),
  
]

MisPerris/MisPerris/apps/mascota/urls.py
from django.urls import path
from apps.mascota.views import index, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
	

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$' ,MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar' ,MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$',MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),
   
]
app_name = 'mascota'

MisPerris/MisPerris/apps/usuario/urls.py
from django.conf.urls import url
from apps.usuario.views import RegistroUsuario
urlpatterns = [
	url(r'^registrar$', RegistroUsuario.as_view(), name='registrar_nuevo'),

]
app_name = 'usuario'

MisPerris/MisPerris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include

urlpatterns = [  
    url('admin/', admin.site.urls),
    url('adopcion/', include ('apps.adopcion.urls',namespace="adopcion")),
    url('mascota/',include ('apps.mascota.urls',namespace="mascota")),
]

MisPerris/MisPerris/apps/adopcion/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    descripcion = models.TextField()
    
    def __str__(self):
        return '{}{}' .format(self.nombre, self.apellido)

class Solicitud(models.Model):
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	numero_mascotas = models.IntegerField()
	razones = models.TextField()

MisPerris/MisPerris/apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

# Create your models here.
class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return '{}' .format(self.nombre)

class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=50)
    edad_aproximada = models.IntegerField() 
    fecha_rescate = models.DateField()  
    Persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

MisPerris/MisPerris/apps/usuario/models.py
from django.db import models

# Create your models here.

MisPerris/MisPerris/apps/adopcion/forms.py
from django import forms
from apps.adopcion.models import Persona, Solicitud

#class PersonaForm(forms.ModelForm):
#
#	class Meta:
#		model = Persona
#		fields = [
#			'nombre',
#			'apellido',
#			'edad',
#			'telefono',
#			'email',
#			'descripcion',
#		]
#		labels = {
#			'nombre': 'Nombre',
#			'apellido': 'Apellidos',
#			'edad': 'Edad',
#			'telefono': 'Telefono',
#			'email': 'Correo Electronico',
#			'descripcion': 'Domicilio',
#		}
#		widgets = {
#			'nombre':forms.TextInput(attrs={'class':'form-control'}),
#			'apellido':forms.TextInput(attrs={'class':'form-control'}),
#			'edad':forms.TextInput(attrs={'class':'form-control'}),
#			'telefono':forms.TextInput(attrs={'class':'form-control'}),
#			'email':forms.TextInput(attrs={'class':'form-control'}),
#			'domicilio':forms.Textarea(attrs={'class':'form-control'}),
#		}
#class SolicitudForm(forms.ModelForm):
#
#	class Meta:
#		model = Solicitud
#		fields = [
##			'numero_mascotas',
###			'razones',
	#	]
#		labels = {
#			'numero_mascotas': 'Numero de mascotas',
#			'razones': 'Razones para adoptar',
#		}
#		widgets = {
#			'numero_mascotas':forms.TextInput(attrs={'class':'form-control'}),
#			'razones':forms.Textarea(attrs={'class':'form-control'}),
#		
#		}

		
		

MisPerris/MisPerris/apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota

        fields =[
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'Persona',
            'vacuna',
        ]
        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad Aproximada',
            'fecha_rescate': 'Fecha de rescate',
            'Persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo':forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada':forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate':forms.TextInput(attrs={'class':'form-control'}),
            'Persona': forms.Select(),
            'Vacuna' : forms.CheckboxSelectMultiple(),
        }

MisPerris/MisPerris/apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):

	class Meta:
		model = User
		fields = [
		'username',
		'first_name',
		'last_name',
		'email',
		]
		labels = {
		'username':'Nombre de usuario',
		'first_name':'Nombre',
		'last_name':'Apellidos',
		'email':'Correo',
		}

MisPerris/MisPerris/apps/adopcion/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView
from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import PersonaForm, SolicitudForm

# Create your views here.
#class SolicitudList(ListView):
#	model = Solicitud
#	template_name = 'adopcion/solicitud_list.html'
#
#class SolicitudCreate(CreateView):
#	model = Solicitud
#	template_name = 'adopcion/solicitud_form.html'		
#	form_class = SolicitudForm
#	second_form_class = PersonaForm
#	succes_url = reverse_lazy('adopcion:solicitud_listar')
#	
#	def get_context_data(self, **kwargs)
#		context = super(SolicitudCreate, self).get_context_data(**kwargs)
#		if 'form' not in context:	
#			context['form'] = self.form_class(self.request.GET)
#		if 'form2' not in context:	
#			context['form2'] = self.second_form_class(self.request.GET)
#		return context
#	def post(self, request, *args, **kwargs):
#       self.object = self.get_object                       
#       form = self.form_class(request.POST)
#	    form2 = self.second_form_class(request.POST)
#       if form.is_valid() and form2.is_valid():
#			solicitud = form.save(commit=False)	
#			solicitud.persona = form2.save()
#           solicitud.save()
#			return HttpResponseRedirect(self.get_succes_url())
#
#

MisPerris/MisPerris/apps/mascota/views.py
from django.shortcuts import render, redirect
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView


# Create your views here.
def index(request):
    return render(request, 'mascota/index.html')
    
class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'
    paginate_by = 2

class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')   

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')   
        

MisPerris/MisPerris/apps/usuario/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from apps.usuario.forms import RegistroForm
# Create your views here.
class RegistroUsuario(CreateView):
	model = User
	template_name = "usuario/registrar.html"
	from_class = RegistroForm
	success_url = reverse_lazy('mascota:mascota_listar')

MisPerris/MisPerris/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es"> 
<head>
<meta charset="UTF-3">
   {% block extrastatic %}
   <style type="text/css">
   .header {background-color: #2f3432}
   .footer {background-color: #2f3432}
   .divUno {background-color: #DB1010}
   </style>
   {% endblock %}
 <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome CSS-->
  <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
  <!-- Google fonts - Roboto-->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  <!-- Bootstrap Select-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
  <!-- owl carousel-->
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">

<title>
{% block title%}
	Mis Perris 
{% endblock %}
	
</title>
</head>

{% block header %}

  <header class="header">
  {% block navbar %}

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <h1 class="text-white">Mis Perris</h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon text-white"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas</a>
                      <ul class="dropdown-menu text-white" role="menu">
                        <li><a class="text-dark" href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
                        <li><a class="text-dark" href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
                      </ul>
                    </li>

                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones</a>
                      <ul class="dropdown-menu text-white" role="menu">
                        <li><a class="text-dark" href="{% url 'mascota:mascota_crear' %}">Solicitar</a></li>
                        <li><a class="text-dark" href="{% url 'mascota:mascota_crear' %}">Listar Solicitudes</a></li>
                      </ul>                     
                    </li>

                  </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown" role="button" aria-expanded="false">Opciones <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a class="text-dark" href="{% url 'logout' %}">Salir</a></li>
                        </ul>
                      </li>
                      <li>
                        
                      </li>
                    </ul>
    </div>
  </nav>
  {% endblock %} 
  </header>
  {% endblock %} 

<body>
<div class="container">
  



    {% block content%}

    {% endblock %}
  

</div>
     <!-- Javascript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
      <script src="{% static 'vendor/waypoints/lib/jquery.waypoints.min.js' %}"> </script>
      <script src="{% static 'vendor/jquery.counterup/jquery.counterup.min.js' %}"> </script>
      <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/jquery.scrollto/jquery.scrollTo.min.js' %}"></script>
    {% block extrajs %}
	
    {% endblock %}
    
</body>
{% block footer %}

  <footer class="footer text-white">
    <div class="container">
      <div class="row">
         <div class="col-md-8">
      <br>
    </div>
  
    <div class="col-md-4">
       <br>
      <address>
         <strong>MisPerris, Inc.</strong><br> 795 Folsom Ave, Suite 600<br> Santiago, Cl<br> <abbr title="Phone">Telefono:</abbr> (+569) 96150697
      </address> <a href="{% url 'mascota:mascota_listar' %}">BackDoor</a>
    </div>
  </div>
    </div>
    

{% endblock %}
</html>

MisPerris/MisPerris/templates/base/header.html
<header>Hola</header>